# Generated by Django 5.1.5 on 2025-05-03 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivosMedicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia_fabricante', models.CharField(blank=True, max_length=40, null=True)),
                ('referencia_lh', models.CharField(blank=True, max_length=40, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_espanol', models.TextField(blank=True, null=True)),
                ('descripcion_ingles', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_registro_sanitario', models.CharField(blank=True, max_length=200, null=True)),
                ('registro_sanitario', models.CharField(max_length=30)),
                ('no_resolucion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('alerta_vencimiento', models.CharField(blank=True, max_length=10, null=True)),
                ('expediente', models.CharField(blank=True, max_length=20, null=True)),
                ('radicado', models.CharField(blank=True, max_length=20, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('titular_registro_sanitario', models.CharField(blank=True, max_length=200, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_fabricante', models.TextField(blank=True, null=True)),
                ('importador', models.CharField(blank=True, max_length=100, null=True)),
                ('acondicionador', models.CharField(blank=True, max_length=100, null=True)),
                ('material_fabricacion', models.TextField(blank=True, null=True)),
                ('clasificacion_riesgo', models.CharField(blank=True, max_length=20, null=True)),
                ('vida_util_anos', models.CharField(blank=True, max_length=40, null=True)),
                ('vida_util_meses', models.CharField(blank=True, max_length=20, null=True)),
                ('presentacion_comercial', models.TextField(blank=True, null=True)),
                ('condiciones_almacenamiento', models.TextField(blank=True, null=True)),
                ('tipo_dispositivo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Dispositivo Médico',
                'verbose_name_plural': 'Dispositivos Médicos',
                'db_table': 'dispositivos_medicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlertaVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=200, verbose_name='Fabricante')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('registro_sanitario', models.CharField(max_length=30, verbose_name='Registro Sanitario')),
            ],
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_lh', models.CharField(help_text='Identificador único para cada licitación.', max_length=100, unique=True, verbose_name='Referencia LH')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Licitación',
                'verbose_name_plural': 'Licitaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LicitacionDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=255, verbose_name='Nombre del campo')),
                ('valor', models.TextField(blank=True, null=True, verbose_name='Valor del campo')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='polls.licitacion', verbose_name='Licitación')),
            ],
            options={
                'verbose_name': 'Dato de Licitación',
                'verbose_name_plural': 'Datos de Licitación',
                'unique_together': {('licitacion', 'campo')},
            },
        ),
    ]
